console.log('This site was generated by Hugo.');

/*
const selector = document.getElementById('selector');
const theme = document.getElementById('theme');

selector.addEventListener('change', (e) => {
  const selected = e.target.value;
  theme.setAttribute('href', `/css/${selected}.css`);
});
*/
